---
#db:
#  dbname: "ccydb"
#  host: "127.0.0.1"
#  port: "5432"
#  user: "postgres"
#  password: "123456"
#  sslmode: "disable"

db:
  dbname: "mysql"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "1234567890"
  sslmode: "disable"